# Generated by Django 4.0.6 on 2022-07-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, unique='True', verbose_name='Número da Conta')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('saldo', models.FloatField(verbose_name='Saldo da Conta')),
                ('cofre', models.FloatField(default=0.0, verbose_name='Valor Guardado')),
            ],
        ),
    ]
